exclude: (vendor|dist)/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.3.0
    hooks:
      - id: commitizen
        additional_dependencies: ["cz-nhm"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v4.0.0-alpha.8'
    hooks:
      - id: prettier
        types_or: [ javascript, vue, less, sass, scss, css ]
        args: [ '--single-quote' ]
